package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpAdministrateur;

import javax.ejb.Remote;
import javax.ejb.Stateful;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrateur generated by hbm2java
 */
@Remote(ImpAdministrateur.class)
@Stateful
@Entity
@Table(name = "administrateur", schema = "public")
public class Administrateur implements java.io.Serializable, ImpAdministrateur {

	private int idutilisateur;
	private Utilisateur utilisateur;
	private String roleoccupeadmin;

	public Administrateur() {
	}

	public Administrateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Administrateur(Utilisateur utilisateur, String roleoccupeadmin) {
		this.utilisateur = utilisateur;
		this.roleoccupeadmin = roleoccupeadmin;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idutilisateur", unique = true, nullable = false)
	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "roleoccupeadmin", length = 32)
	public String getRoleoccupeadmin() {
		return this.roleoccupeadmin;
	}

	public void setRoleoccupeadmin(String roleoccupeadmin) {
		this.roleoccupeadmin = roleoccupeadmin;
	}

}
