package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpAnneeetude;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Anneeetude generated by hbm2java
 */
@Stateless
@Remote(ImpAnneeetude.class)
@Entity
@Table(name = "anneeetude", schema = "public")
public class Anneeetude implements java.io.Serializable, ImpAnneeetude {

	private Date aaaa;
	private Set<Suivreformation> suivreformations = new HashSet<Suivreformation>(0);

	public Anneeetude() {
	}

	public Anneeetude(Date aaaa) {
		this.aaaa = aaaa;
	}

	public Anneeetude(Date aaaa, Set<Suivreformation> suivreformations) {
		this.aaaa = aaaa;
		this.suivreformations = suivreformations;
	}

	@Id

	@Temporal(TemporalType.DATE)
	@Column(name = "aaaa", unique = true, nullable = false, length = 13)
	public Date getAaaa() {
		return this.aaaa;
	}

	public void setAaaa(Date aaaa) {
		this.aaaa = aaaa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeetude")
	public Set<Suivreformation> getSuivreformations() {
		return this.suivreformations;
	}

	public void setSuivreformations(Set<Suivreformation> suivreformations) {
		this.suivreformations = suivreformations;
	}

}
