package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpDatecontrat;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datecontrat generated by hbm2java
 */
@Stateless
@Remote(ImpDatecontrat.class)
@Entity
@Table(name = "datecontrat", schema = "public")
public class Datecontrat implements java.io.Serializable, ImpDatecontrat {

	private Date mmaa;
	private Set<Detenirposte> detenirpostes = new HashSet<Detenirposte>(0);

	public Datecontrat() {
	}

	public Datecontrat(Date mmaa) {
		this.mmaa = mmaa;
	}

	public Datecontrat(Date mmaa, Set<Detenirposte> detenirpostes) {
		this.mmaa = mmaa;
		this.detenirpostes = detenirpostes;
	}

	@Id

	@Temporal(TemporalType.DATE)
	@Column(name = "mmaa", unique = true, nullable = false, length = 13)
	public Date getMmaa() {
		return this.mmaa;
	}

	public void setMmaa(Date mmaa) {
		this.mmaa = mmaa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datecontrat")
	public Set<Detenirposte> getDetenirpostes() {
		return this.detenirpostes;
	}

	public void setDetenirpostes(Set<Detenirposte> detenirpostes) {
		this.detenirpostes = detenirpostes;
	}

}
