package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetenirposteId generated by hbm2java
 */
@Embeddable
public class DetenirposteId implements java.io.Serializable {

	private int idutilisateur;
	private int idposte;
	private Date mmaa;

	public DetenirposteId() {
	}

	public DetenirposteId(int idutilisateur, int idposte, Date mmaa) {
		this.idutilisateur = idutilisateur;
		this.idposte = idposte;
		this.mmaa = mmaa;
	}

	@Column(name = "idutilisateur", nullable = false)
	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@Column(name = "idposte", nullable = false)
	public int getIdposte() {
		return this.idposte;
	}

	public void setIdposte(int idposte) {
		this.idposte = idposte;
	}

	@Column(name = "mmaa", nullable = false, length = 13)
	public Date getMmaa() {
		return this.mmaa;
	}

	public void setMmaa(Date mmaa) {
		this.mmaa = mmaa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetenirposteId))
			return false;
		DetenirposteId castOther = (DetenirposteId) other;

		return (this.getIdutilisateur() == castOther.getIdutilisateur())
				&& (this.getIdposte() == castOther.getIdposte())
				&& ((this.getMmaa() == castOther.getMmaa()) || (this.getMmaa() != null && castOther.getMmaa() != null
						&& this.getMmaa().equals(castOther.getMmaa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdutilisateur();
		result = 37 * result + this.getIdposte();
		result = 37 * result + (getMmaa() == null ? 0 : this.getMmaa().hashCode());
		return result;
	}

}
