package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpDomaine;

import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domaine generated by hbm2java
 */
@Stateless
@Remote(ImpDomaine.class)
@Entity
@Table(name = "domaine", schema = "public")
public class Domaine implements java.io.Serializable, ImpDomaine {

	private String iddomaine;
	private String libelledomaine;
	private Set<Offre> offres = new HashSet<Offre>(0);

	public Domaine() {
	}

	public Domaine(String iddomaine, String libelledomaine) {
		this.iddomaine = iddomaine;
		this.libelledomaine = libelledomaine;
	}

	public Domaine(String iddomaine, String libelledomaine, Set<Offre> offres) {
		this.iddomaine = iddomaine;
		this.libelledomaine = libelledomaine;
		this.offres = offres;
	}

	@Id

	@Column(name = "iddomaine", unique = true, nullable = false, length = 32)
	public String getIddomaine() {
		return this.iddomaine;
	}

	public void setIddomaine(String iddomaine) {
		this.iddomaine = iddomaine;
	}

	@Column(name = "libelledomaine", nullable = false, length = 32)
	public String getLibelledomaine() {
		return this.libelledomaine;
	}

	public void setLibelledomaine(String libelledomaine) {
		this.libelledomaine = libelledomaine;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domaine")
	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

}
