package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpEntreprise;

import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entreprise generated by hbm2java
 */
@Stateless
@Remote(ImpEntreprise.class)
@Entity
@Table(name = "entreprise", schema = "public")
public class Entreprise implements java.io.Serializable, ImpEntreprise {

	private String identreprise;
	private String nomentreprise;
	private String numeroadresseentreprise;
	private String adresseentreprise;
	private String codepostalentreprise;
	private String villeentreprise;
	private String paysentreprise;
	private String logoentreprise;
	private String descriptionentreprise;
	private Set<Recruteur> recruteurs = new HashSet<Recruteur>(0);

	public Entreprise() {
	}

	public Entreprise(String identreprise, String villeentreprise, String paysentreprise) {
		this.identreprise = identreprise;
		this.villeentreprise = villeentreprise;
		this.paysentreprise = paysentreprise;
	}

	public Entreprise(String identreprise, String nomentreprise, String numeroadresseentreprise,
			String adresseentreprise, String codepostalentreprise, String villeentreprise, String paysentreprise,
			String logoentreprise, String descriptionentreprise, Set<Recruteur> recruteurs) {
		this.identreprise = identreprise;
		this.nomentreprise = nomentreprise;
		this.numeroadresseentreprise = numeroadresseentreprise;
		this.adresseentreprise = adresseentreprise;
		this.codepostalentreprise = codepostalentreprise;
		this.villeentreprise = villeentreprise;
		this.paysentreprise = paysentreprise;
		this.logoentreprise = logoentreprise;
		this.descriptionentreprise = descriptionentreprise;
		this.recruteurs = recruteurs;
	}

	@Id

	@Column(name = "identreprise", unique = true, nullable = false, length = 32)
	public String getIdentreprise() {
		return this.identreprise;
	}

	public void setIdentreprise(String identreprise) {
		this.identreprise = identreprise;
	}

	@Column(name = "nomentreprise", length = 32)
	public String getNomentreprise() {
		return this.nomentreprise;
	}

	public void setNomentreprise(String nomentreprise) {
		this.nomentreprise = nomentreprise;
	}

	@Column(name = "numeroadresseentreprise", length = 32)
	public String getNumeroadresseentreprise() {
		return this.numeroadresseentreprise;
	}

	public void setNumeroadresseentreprise(String numeroadresseentreprise) {
		this.numeroadresseentreprise = numeroadresseentreprise;
	}

	@Column(name = "adresseentreprise", length = 32)
	public String getAdresseentreprise() {
		return this.adresseentreprise;
	}

	public void setAdresseentreprise(String adresseentreprise) {
		this.adresseentreprise = adresseentreprise;
	}

	@Column(name = "codepostalentreprise", length = 32)
	public String getCodepostalentreprise() {
		return this.codepostalentreprise;
	}

	public void setCodepostalentreprise(String codepostalentreprise) {
		this.codepostalentreprise = codepostalentreprise;
	}

	@Column(name = "villeentreprise", nullable = false, length = 32)
	public String getVilleentreprise() {
		return this.villeentreprise;
	}

	public void setVilleentreprise(String villeentreprise) {
		this.villeentreprise = villeentreprise;
	}

	@Column(name = "paysentreprise", nullable = false, length = 32)
	public String getPaysentreprise() {
		return this.paysentreprise;
	}

	public void setPaysentreprise(String paysentreprise) {
		this.paysentreprise = paysentreprise;
	}

	@Column(name = "logoentreprise")
	public String getLogoentreprise() {
		return this.logoentreprise;
	}

	public void setLogoentreprise(String logoentreprise) {
		this.logoentreprise = logoentreprise;
	}

	@Column(name = "descriptionentreprise")
	public String getDescriptionentreprise() {
		return this.descriptionentreprise;
	}

	public void setDescriptionentreprise(String descriptionentreprise) {
		this.descriptionentreprise = descriptionentreprise;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entreprise")
	public Set<Recruteur> getRecruteurs() {
		return this.recruteurs;
	}

	public void setRecruteurs(Set<Recruteur> recruteurs) {
		this.recruteurs = recruteurs;
	}

}
