package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpEvenement;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evenement generated by hbm2java
 */
@Stateless
@Remote(ImpEvenement.class)
@Entity
@Table(name = "evenement", schema = "public")
public class Evenement implements java.io.Serializable, ImpEvenement {

	private int idevenement;
	private String etatevenement;
	private String libelleevenement;
	private Date datedebutevenement;
	private Set<ParticiperEvenement> participerEvenements = new HashSet<ParticiperEvenement>(0);

	public Evenement() {
	}

	public Evenement(int idevenement, String etatevenement, String libelleevenement, Date datedebutevenement) {
		this.idevenement = idevenement;
		this.etatevenement = etatevenement;
		this.libelleevenement = libelleevenement;
		this.datedebutevenement = datedebutevenement;
	}

	public Evenement(int idevenement, String etatevenement, String libelleevenement, Date datedebutevenement,
			Set<ParticiperEvenement> participerEvenements) {
		this.idevenement = idevenement;
		this.etatevenement = etatevenement;
		this.libelleevenement = libelleevenement;
		this.datedebutevenement = datedebutevenement;
		this.participerEvenements = participerEvenements;
	}

	@Id

	@Column(name = "idevenement", unique = true, nullable = false)
	public int getIdevenement() {
		return this.idevenement;
	}

	public void setIdevenement(int idevenement) {
		this.idevenement = idevenement;
	}

	@Column(name = "etatevenement", nullable = false)
	public String getEtatevenement() {
		return this.etatevenement;
	}

	public void setEtatevenement(String etatevenement) {
		this.etatevenement = etatevenement;
	}

	@Column(name = "libelleevenement", nullable = false)
	public String getLibelleevenement() {
		return this.libelleevenement;
	}

	public void setLibelleevenement(String libelleevenement) {
		this.libelleevenement = libelleevenement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datedebutevenement", nullable = false, length = 13)
	public Date getDatedebutevenement() {
		return this.datedebutevenement;
	}

	public void setDatedebutevenement(Date datedebutevenement) {
		this.datedebutevenement = datedebutevenement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evenement")
	public Set<ParticiperEvenement> getParticiperEvenements() {
		return this.participerEvenements;
	}

	public void setParticiperEvenements(Set<ParticiperEvenement> participerEvenements) {
		this.participerEvenements = participerEvenements;
	}

}
