package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpExigerCompetence;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExigerCompetence generated by hbm2java
 */
@Stateless
@Remote(ImpExigerCompetence.class)
@Entity
@Table(name = "exiger_competence", schema = "public")
public class ExigerCompetence implements java.io.Serializable, ImpExigerCompetence {

	private ExigerCompetenceId id;
	private Competence competence;
	private Offre offre;
	private Character libelle;

	public ExigerCompetence() {
	}

	public ExigerCompetence(ExigerCompetenceId id, Competence competence, Offre offre) {
		this.id = id;
		this.competence = competence;
		this.offre = offre;
	}

	public ExigerCompetence(ExigerCompetenceId id, Competence competence, Offre offre, Character libelle) {
		this.id = id;
		this.competence = competence;
		this.offre = offre;
		this.libelle = libelle;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idcompetence", column = @Column(name = "idcompetence", nullable = false) ),
			@AttributeOverride(name = "idoffre", column = @Column(name = "idoffre", nullable = false) ) })
	public ExigerCompetenceId getId() {
		return this.id;
	}

	public void setId(ExigerCompetenceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompetence", nullable = false, insertable = false, updatable = false)
	public Competence getCompetence() {
		return this.competence;
	}

	public void setCompetence(Competence competence) {
		this.competence = competence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoffre", nullable = false, insertable = false, updatable = false)
	public Offre getOffre() {
		return this.offre;
	}

	public void setOffre(Offre offre) {
		this.offre = offre;
	}

	@Column(name = "libelle", length = 1)
	public Character getLibelle() {
		return this.libelle;
	}

	public void setLibelle(Character libelle) {
		this.libelle = libelle;
	}

}
