package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExigerCompetenceId generated by hbm2java
 */
@Embeddable
public class ExigerCompetenceId implements java.io.Serializable {

	private int idcompetence;
	private int idoffre;

	public ExigerCompetenceId() {
	}

	public ExigerCompetenceId(int idcompetence, int idoffre) {
		this.idcompetence = idcompetence;
		this.idoffre = idoffre;
	}

	@Column(name = "idcompetence", nullable = false)
	public int getIdcompetence() {
		return this.idcompetence;
	}

	public void setIdcompetence(int idcompetence) {
		this.idcompetence = idcompetence;
	}

	@Column(name = "idoffre", nullable = false)
	public int getIdoffre() {
		return this.idoffre;
	}

	public void setIdoffre(int idoffre) {
		this.idoffre = idoffre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExigerCompetenceId))
			return false;
		ExigerCompetenceId castOther = (ExigerCompetenceId) other;

		return (this.getIdcompetence() == castOther.getIdcompetence()) && (this.getIdoffre() == castOther.getIdoffre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcompetence();
		result = 37 * result + this.getIdoffre();
		return result;
	}

}
