package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpFichier;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fichier generated by hbm2java
 */
@Stateless
@Remote(ImpFichier.class)
@Entity
@Table(name = "fichier", schema = "public")
public class Fichier implements java.io.Serializable, ImpFichier {

	private String idfichier;
	private Utilisateur utilisateur;
	private String contenufichier;

	public Fichier() {
	}

	public Fichier(String idfichier, Utilisateur utilisateur) {
		this.idfichier = idfichier;
		this.utilisateur = utilisateur;
	}

	public Fichier(String idfichier, Utilisateur utilisateur, String contenufichier) {
		this.idfichier = idfichier;
		this.utilisateur = utilisateur;
		this.contenufichier = contenufichier;
	}

	@Id

	@Column(name = "idfichier", unique = true, nullable = false, length = 32)
	public String getIdfichier() {
		return this.idfichier;
	}

	public void setIdfichier(String idfichier) {
		this.idfichier = idfichier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "contenufichier", length = 32)
	public String getContenufichier() {
		return this.contenufichier;
	}

	public void setContenufichier(String contenufichier) {
		this.contenufichier = contenufichier;
	}

}
