package beans;
// Generated 22 nov. 2015 15:00:06 by Hibernate Tools 4.3.1.Final

import interfaces.ImpFormation;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formation generated by hbm2java
 */
@Stateless
@Remote(ImpFormation.class)
@Entity
@Table(name = "formation", schema = "public")
public class Formation implements java.io.Serializable, ImpFormation {

	private int idformation;
	private String libelleformation;
	private String ecoleformation;
	private Date anneeformation;
	private Set<Suivreformation> suivreformations = new HashSet<Suivreformation>(0);

	public Formation() {
	}

	public Formation(int idformation, String libelleformation, String ecoleformation) {
		this.idformation = idformation;
		this.libelleformation = libelleformation;
		this.ecoleformation = ecoleformation;
	}

	public Formation(int idformation, String libelleformation, String ecoleformation, Date anneeformation,
			Set<Suivreformation> suivreformations) {
		this.idformation = idformation;
		this.libelleformation = libelleformation;
		this.ecoleformation = ecoleformation;
		this.anneeformation = anneeformation;
		this.suivreformations = suivreformations;
	}

	@Id

	@Column(name = "idformation", unique = true, nullable = false)
	public int getIdformation() {
		return this.idformation;
	}

	public void setIdformation(int idformation) {
		this.idformation = idformation;
	}

	@Column(name = "libelleformation", nullable = false)
	public String getLibelleformation() {
		return this.libelleformation;
	}

	public void setLibelleformation(String libelleformation) {
		this.libelleformation = libelleformation;
	}

	@Column(name = "ecoleformation", nullable = false)
	public String getEcoleformation() {
		return this.ecoleformation;
	}

	public void setEcoleformation(String ecoleformation) {
		this.ecoleformation = ecoleformation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anneeformation", length = 13)
	public Date getAnneeformation() {
		return this.anneeformation;
	}

	public void setAnneeformation(Date anneeformation) {
		this.anneeformation = anneeformation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formation")
	public Set<Suivreformation> getSuivreformations() {
		return this.suivreformations;
	}

	public void setSuivreformations(Set<Suivreformation> suivreformations) {
		this.suivreformations = suivreformations;
	}

}
