package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import interfaces.ImpMetier;

/**
 * Metier generated by hbm2java
 */

@Stateless
@Remote(ImpMetier.class)

@Entity
@Table(name = "metier", schema = "public")
public class Metier implements java.io.Serializable, ImpMetier {

	private int idmetier;
	private String libellemetier;
	private Set<OccuperMetier> occuperMetiers = new HashSet<OccuperMetier>(0);

	public Metier() {
	}

	public Metier(int idmetier, String libellemetier) {
		this.idmetier = idmetier;
		this.libellemetier = libellemetier;
	}

	public Metier(int idmetier, String libellemetier, Set<OccuperMetier> occuperMetiers) {
		this.idmetier = idmetier;
		this.libellemetier = libellemetier;
		this.occuperMetiers = occuperMetiers;
	}

	@Id

	@Column(name = "idmetier", unique = true, nullable = false)
	public int getIdmetier() {
		return this.idmetier;
	}

	public void setIdmetier(int idmetier) {
		this.idmetier = idmetier;
	}

	@Column(name = "libellemetier", nullable = false)
	public String getLibellemetier() {
		return this.libellemetier;
	}

	public void setLibellemetier(String libellemetier) {
		this.libellemetier = libellemetier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metier")
	public Set<OccuperMetier> getOccuperMetiers() {
		return this.occuperMetiers;
	}

	public void setOccuperMetiers(Set<OccuperMetier> occuperMetiers) {
		this.occuperMetiers = occuperMetiers;
	}

}
