package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import interfaces.ImpOccuperMetier;

/**
 * OccuperMetier generated by hbm2java
 */

@Stateless
@Remote(ImpOccuperMetier.class)
@Entity
@Table(name = "occuper_metier", schema = "public")
public class OccuperMetier implements java.io.Serializable, ImpOccuperMetier {

	private OccuperMetierId id;
	private Metier metier;
	private Utilisateur utilisateur;
	private Character libelle;

	public OccuperMetier() {
	}

	public OccuperMetier(OccuperMetierId id, Metier metier, Utilisateur utilisateur) {
		this.id = id;
		this.metier = metier;
		this.utilisateur = utilisateur;
	}

	public OccuperMetier(OccuperMetierId id, Metier metier, Utilisateur utilisateur, Character libelle) {
		this.id = id;
		this.metier = metier;
		this.utilisateur = utilisateur;
		this.libelle = libelle;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idutilisateur", column = @Column(name = "idutilisateur", nullable = false) ),
			@AttributeOverride(name = "idmetier", column = @Column(name = "idmetier", nullable = false) ) })
	public OccuperMetierId getId() {
		return this.id;
	}

	public void setId(OccuperMetierId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmetier", nullable = false, insertable = false, updatable = false)
	public Metier getMetier() {
		return this.metier;
	}

	public void setMetier(Metier metier) {
		this.metier = metier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutilisateur", nullable = false, insertable = false, updatable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "libelle", length = 1)
	public Character getLibelle() {
		return this.libelle;
	}

	public void setLibelle(Character libelle) {
		this.libelle = libelle;
	}

}
