package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PostulerOffreId generated by hbm2java
 */
@Embeddable
public class PostulerOffreId implements java.io.Serializable {

	private int idutilisateur;
	private int idoffre;

	public PostulerOffreId() {
	}

	public PostulerOffreId(int idutilisateur, int idoffre) {
		this.idutilisateur = idutilisateur;
		this.idoffre = idoffre;
	}

	@Column(name = "idutilisateur", nullable = false)
	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@Column(name = "idoffre", nullable = false)
	public int getIdoffre() {
		return this.idoffre;
	}

	public void setIdoffre(int idoffre) {
		this.idoffre = idoffre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PostulerOffreId))
			return false;
		PostulerOffreId castOther = (PostulerOffreId) other;

		return (this.getIdutilisateur() == castOther.getIdutilisateur())
				&& (this.getIdoffre() == castOther.getIdoffre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdutilisateur();
		result = 37 * result + this.getIdoffre();
		return result;
	}

}
