package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SuivreformationId generated by hbm2java
 */
@Embeddable
public class SuivreformationId implements java.io.Serializable {

	private int idutilisateur;
	private int idformation;
	private Date aaaa;

	public SuivreformationId() {
	}

	public SuivreformationId(int idutilisateur, int idformation, Date aaaa) {
		this.idutilisateur = idutilisateur;
		this.idformation = idformation;
		this.aaaa = aaaa;
	}

	@Column(name = "idutilisateur", nullable = false)
	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@Column(name = "idformation", nullable = false)
	public int getIdformation() {
		return this.idformation;
	}

	public void setIdformation(int idformation) {
		this.idformation = idformation;
	}

	@Column(name = "aaaa", nullable = false, length = 13)
	public Date getAaaa() {
		return this.aaaa;
	}

	public void setAaaa(Date aaaa) {
		this.aaaa = aaaa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SuivreformationId))
			return false;
		SuivreformationId castOther = (SuivreformationId) other;

		return (this.getIdutilisateur() == castOther.getIdutilisateur())
				&& (this.getIdformation() == castOther.getIdformation())
				&& ((this.getAaaa() == castOther.getAaaa()) || (this.getAaaa() != null && castOther.getAaaa() != null
						&& this.getAaaa().equals(castOther.getAaaa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdutilisateur();
		result = 37 * result + this.getIdformation();
		result = 37 * result + (getAaaa() == null ? 0 : this.getAaaa().hashCode());
		return result;
	}

}
