package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import javax.ejb.Remote;
import javax.ejb.Stateful;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import interfaces.ImpSuivreformation;

/**
 * Suivreformation generated by hbm2java
 */

@Stateful
@Remote(ImpSuivreformation.class)

@Entity
@Table(name = "suivreformation", schema = "public")
public class Suivreformation implements java.io.Serializable, ImpSuivreformation {

	private SuivreformationId id;
	private Anneeetude anneeetude;
	private Etudiant etudiant;
	private Formation formation;
	private String anneefinformationsuivie;

	public Suivreformation() {
	}

	public Suivreformation(SuivreformationId id, Anneeetude anneeetude, Etudiant etudiant, Formation formation) {
		this.id = id;
		this.anneeetude = anneeetude;
		this.etudiant = etudiant;
		this.formation = formation;
	}

	public Suivreformation(SuivreformationId id, Anneeetude anneeetude, Etudiant etudiant, Formation formation,
			String anneefinformationsuivie) {
		this.id = id;
		this.anneeetude = anneeetude;
		this.etudiant = etudiant;
		this.formation = formation;
		this.anneefinformationsuivie = anneefinformationsuivie;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idutilisateur", column = @Column(name = "idutilisateur", nullable = false) ),
			@AttributeOverride(name = "idformation", column = @Column(name = "idformation", nullable = false) ),
			@AttributeOverride(name = "aaaa", column = @Column(name = "aaaa", nullable = false, length = 13) ) })
	public SuivreformationId getId() {
		return this.id;
	}

	public void setId(SuivreformationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aaaa", nullable = false, insertable = false, updatable = false)
	public Anneeetude getAnneeetude() {
		return this.anneeetude;
	}

	public void setAnneeetude(Anneeetude anneeetude) {
		this.anneeetude = anneeetude;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idutilisateur", nullable = false, insertable = false, updatable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idformation", nullable = false, insertable = false, updatable = false)
	public Formation getFormation() {
		return this.formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	@Column(name = "anneefinformationsuivie", length = 32)
	public String getAnneefinformationsuivie() {
		return this.anneefinformationsuivie;
	}

	public void setAnneefinformationsuivie(String anneefinformationsuivie) {
		this.anneefinformationsuivie = anneefinformationsuivie;
	}

}
