package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import interfaces.ImpTypeposte;

/**
 * Typeposte generated by hbm2java
 */

@Stateless
@Remote(ImpTypeposte.class)

@Entity
@Table(name = "typeposte", schema = "public")
public class Typeposte implements java.io.Serializable, ImpTypeposte {

	private int idposte;
	private String libelleposte;
	private Set<ProposerPoste> proposerPostes = new HashSet<ProposerPoste>(0);
	private Set<Detenirposte> detenirpostes = new HashSet<Detenirposte>(0);

	public Typeposte() {
	}

	public Typeposte(int idposte, String libelleposte) {
		this.idposte = idposte;
		this.libelleposte = libelleposte;
	}

	public Typeposte(int idposte, String libelleposte, Set<ProposerPoste> proposerPostes,
			Set<Detenirposte> detenirpostes) {
		this.idposte = idposte;
		this.libelleposte = libelleposte;
		this.proposerPostes = proposerPostes;
		this.detenirpostes = detenirpostes;
	}

	@Id

	@Column(name = "idposte", unique = true, nullable = false)
	public int getIdposte() {
		return this.idposte;
	}

	public void setIdposte(int idposte) {
		this.idposte = idposte;
	}

	@Column(name = "libelleposte", nullable = false)
	public String getLibelleposte() {
		return this.libelleposte;
	}

	public void setLibelleposte(String libelleposte) {
		this.libelleposte = libelleposte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeposte")
	public Set<ProposerPoste> getProposerPostes() {
		return this.proposerPostes;
	}

	public void setProposerPostes(Set<ProposerPoste> proposerPostes) {
		this.proposerPostes = proposerPostes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeposte")
	public Set<Detenirposte> getDetenirpostes() {
		return this.detenirpostes;
	}

	public void setDetenirpostes(Set<Detenirposte> detenirpostes) {
		this.detenirpostes = detenirpostes;
	}

}
