package beans;
// Generated 24 nov. 2015 11:14:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import interfaces.ImpVille;

/**
 * Ville generated by hbm2java
 */

@Stateless
@Remote(ImpVille.class)

@Entity
@Table(name = "ville", schema = "public")
public class Ville implements java.io.Serializable, ImpVille {

	private String idville;
	private Region region;
	private String libelleville;
	private Set<Offre> offres = new HashSet<Offre>(0);

	public Ville() {
	}

	public Ville(String idville, Region region, String libelleville) {
		this.idville = idville;
		this.region = region;
		this.libelleville = libelleville;
	}

	public Ville(String idville, Region region, String libelleville, Set<Offre> offres) {
		this.idville = idville;
		this.region = region;
		this.libelleville = libelleville;
		this.offres = offres;
	}

	@Id

	@Column(name = "idville", unique = true, nullable = false, length = 32)
	public String getIdville() {
		return this.idville;
	}

	public void setIdville(String idville) {
		this.idville = idville;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idregion", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "libelleville", nullable = false, length = 32)
	public String getLibelleville() {
		return this.libelleville;
	}

	public void setLibelleville(String libelleville) {
		this.libelleville = libelleville;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

}
